# Generated by Django 5.1.7 on 2025-04-08 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('nazwa', models.TextField()),
                ('smiles', models.TextField()),
                ('smiles1', models.TextField(default='')),
                ('smiles2', models.TextField(default='')),
                ('cieplo', models.FloatField(default=0)),
                ('energia', models.FloatField(default=0)),
                ('cieplo1', models.FloatField(default=0)),
                ('energia1', models.FloatField(default=0)),
                ('cieplo2', models.FloatField(default=0)),
                ('energia2', models.FloatField(default=0)),
                ('metoda', models.TextField()),
                ('calculated', models.BooleanField(default=False)),
                ('calculations', models.TextField()),
                ('vibration_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
